from __future__ import annotations

from dataclasses import dataclass


CANONICAL_AXES = (
    "focus_readiness",
    "stress_load",
    "fatigue_risk",
    "relaxation_level",
    "cortical_arousal",
    "mental_workload",
)


@dataclass(frozen=True, slots=True)
class PlanetProfile:
    slug: str
    title: str
    goal_label: str
    user_description: str
    category: str
    session_duration_sec: int
    target_axes: dict[str, float]
    style_bias: dict[str, float]
    lighting_defaults: dict[str, object]
    music_defaults: dict[str, object]


PLANET_PROFILES: dict[str, PlanetProfile] = {
    "mercury": PlanetProfile(
        slug="mercury",
        title="Mercury",
        goal_label="순간 점화 집중",
        user_description="망설임을 줄이고 빠르게 시작할 수 있도록 돕는 환경입니다. 짧은 시간 안에 집중을 켜고, 작업 진입 속도를 끌어올리고 싶을 때 적합합니다.",
        category="activation-focus",
        session_duration_sec=480,
        target_axes={
            "focus_readiness": 0.82,
            "stress_load": 0.28,
            "fatigue_risk": 0.18,
            "relaxation_level": 0.32,
            "cortical_arousal": 0.78,
            "mental_workload": 0.56,
        },
        style_bias={"warmth": 0.48, "novelty": 0.24, "motion": 0.74, "density": 0.46},
        lighting_defaults={
            "primary_hex": "#ffd36b",
            "secondary_hex": "#ff9b54",
            "accent_hex": "#fff1c6",
            "brightness_percent": 72,
            "cct_kelvin": 4700,
            "motion_intensity": 0.72,
            "pulse_bpm": 102,
            "pattern": "ignite-pulse",
        },
        music_defaults={
            "bpm_target": 102,
            "bpm_min": 96,
            "bpm_max": 112,
            "key_scale": "D Minor",
            "time_signature": "4",
            "energy": 0.62,
            "rhythmic_density": 0.54,
            "spectral_brightness": 0.58,
            "harmonic_tension": 0.42,
            "repetition": 0.60,
            "texture_density": 0.40,
            "dynamic_range": 0.36,
            "attack_softness": 0.46,
            "instruments": ["tight pulse synth", "soft percussive ticks", "filtered bass", "focused arpeggio"],
            "avoid": ["heavy vocals", "chaotic drums", "wide reverb wash"],
        },
    ),
    "venus": PlanetProfile(
        slug="venus",
        title="Venus",
        goal_label="온기 있는 창의",
        user_description="감각과 감정을 부드럽게 깨워 아이디어가 자연스럽게 흐르도록 돕는 환경입니다. 글쓰기, 디자인, 브랜딩처럼 섬세한 표현과 연상이 필요한 순간에 어울립니다.",
        category="warm-creativity",
        session_duration_sec=720,
        target_axes={
            "focus_readiness": 0.58,
            "stress_load": 0.22,
            "fatigue_risk": 0.30,
            "relaxation_level": 0.64,
            "cortical_arousal": 0.47,
            "mental_workload": 0.34,
        },
        style_bias={"warmth": 0.84, "novelty": 0.54, "motion": 0.34, "density": 0.42},
        lighting_defaults={
            "primary_hex": "#ffb8c8",
            "secondary_hex": "#ffd7a8",
            "accent_hex": "#ffeeda",
            "brightness_percent": 50,
            "cct_kelvin": 3250,
            "motion_intensity": 0.34,
            "pulse_bpm": 76,
            "pattern": "warm-bloom",
        },
        music_defaults={
            "bpm_target": 78,
            "bpm_min": 70,
            "bpm_max": 86,
            "key_scale": "F Major",
            "time_signature": "4",
            "energy": 0.38,
            "rhythmic_density": 0.24,
            "spectral_brightness": 0.46,
            "harmonic_tension": 0.28,
            "repetition": 0.58,
            "texture_density": 0.50,
            "dynamic_range": 0.28,
            "attack_softness": 0.78,
            "instruments": ["felt piano", "warm synth pad", "soft plucked texture", "gentle pulse"],
            "avoid": ["harsh transients", "aggressive bass", "club drums"],
        },
    ),
    "earth": PlanetProfile(
        slug="earth",
        title="Earth",
        goal_label="균형형 집중",
        user_description="과하게 긴장하지 않으면서도 안정적으로 집중을 유지하도록 설계된 환경입니다. 장시간 업무, 학습, 루틴 작업을 편안하게 이어가고 싶을 때 적합합니다.",
        category="balanced-focus",
        session_duration_sec=900,
        target_axes={
            "focus_readiness": 0.72,
            "stress_load": 0.22,
            "fatigue_risk": 0.25,
            "relaxation_level": 0.54,
            "cortical_arousal": 0.52,
            "mental_workload": 0.48,
        },
        style_bias={"warmth": 0.58, "novelty": 0.22, "motion": 0.44, "density": 0.40},
        lighting_defaults={
            "primary_hex": "#8fe3c2",
            "secondary_hex": "#8db5ff",
            "accent_hex": "#dff6ec",
            "brightness_percent": 56,
            "cct_kelvin": 4200,
            "motion_intensity": 0.42,
            "pulse_bpm": 78,
            "pattern": "steady-breath",
        },
        music_defaults={
            "bpm_target": 78,
            "bpm_min": 72,
            "bpm_max": 84,
            "key_scale": "C Major",
            "time_signature": "4",
            "energy": 0.44,
            "rhythmic_density": 0.30,
            "spectral_brightness": 0.40,
            "harmonic_tension": 0.22,
            "repetition": 0.70,
            "texture_density": 0.38,
            "dynamic_range": 0.26,
            "attack_softness": 0.72,
            "instruments": ["steady pad", "subtle piano", "low pulse", "soft noise bed"],
            "avoid": ["sudden drops", "vocal hooks", "excessive cymbals"],
        },
    ),
    "mars": PlanetProfile(
        slug="mars",
        title="Mars",
        goal_label="결단과 실행",
        user_description="미루고 있던 일을 바로 행동으로 옮길 수 있도록 추진력을 높이는 환경입니다. 빠른 결단, 실행, 돌파가 필요한 순간에 가장 잘 맞습니다.",
        category="action-drive",
        session_duration_sec=600,
        target_axes={
            "focus_readiness": 0.84,
            "stress_load": 0.42,
            "fatigue_risk": 0.16,
            "relaxation_level": 0.18,
            "cortical_arousal": 0.86,
            "mental_workload": 0.62,
        },
        style_bias={"warmth": 0.62, "novelty": 0.26, "motion": 0.88, "density": 0.56},
        lighting_defaults={
            "primary_hex": "#ff7459",
            "secondary_hex": "#ffbf7a",
            "accent_hex": "#fff2d4",
            "brightness_percent": 78,
            "cct_kelvin": 4200,
            "motion_intensity": 0.86,
            "pulse_bpm": 116,
            "pattern": "forward-thrust",
        },
        music_defaults={
            "bpm_target": 112,
            "bpm_min": 100,
            "bpm_max": 122,
            "key_scale": "E Minor",
            "time_signature": "4",
            "energy": 0.72,
            "rhythmic_density": 0.60,
            "spectral_brightness": 0.56,
            "harmonic_tension": 0.48,
            "repetition": 0.64,
            "texture_density": 0.48,
            "dynamic_range": 0.40,
            "attack_softness": 0.38,
            "instruments": ["driving pulse", "focused synth bass", "tight percussion", "motivational riser"],
            "avoid": ["slow ambient wash", "whisper vocals", "sleepy pads"],
        },
    ),
    "jupiter": PlanetProfile(
        slug="jupiter",
        title="Jupiter",
        goal_label="전략적 존재감",
        user_description="큰 그림을 보고 판단의 중심을 잡을 수 있도록 돕는 환경입니다. 중요한 선택, 발표 준비, 리더십이 필요한 상황에서 넓고 단단한 사고를 지원합니다.",
        category="strategic-presence",
        session_duration_sec=720,
        target_axes={
            "focus_readiness": 0.74,
            "stress_load": 0.32,
            "fatigue_risk": 0.18,
            "relaxation_level": 0.38,
            "cortical_arousal": 0.72,
            "mental_workload": 0.55,
        },
        style_bias={"warmth": 0.44, "novelty": 0.32, "motion": 0.58, "density": 0.54},
        lighting_defaults={
            "primary_hex": "#f0c46a",
            "secondary_hex": "#d7b0ff",
            "accent_hex": "#fff4d6",
            "brightness_percent": 64,
            "cct_kelvin": 4400,
            "motion_intensity": 0.56,
            "pulse_bpm": 92,
            "pattern": "command-wave",
        },
        music_defaults={
            "bpm_target": 92,
            "bpm_min": 84,
            "bpm_max": 100,
            "key_scale": "G Minor",
            "time_signature": "4",
            "energy": 0.58,
            "rhythmic_density": 0.42,
            "spectral_brightness": 0.46,
            "harmonic_tension": 0.34,
            "repetition": 0.66,
            "texture_density": 0.48,
            "dynamic_range": 0.34,
            "attack_softness": 0.52,
            "instruments": ["broad pad", "steady low tom pulse", "cinematic brass texture", "controlled arpeggio"],
            "avoid": ["chaotic glitch", "cute plucks", "hyperpop drums"],
        },
    ),
    "saturn": PlanetProfile(
        slug="saturn",
        title="Saturn",
        goal_label="깊은 사유",
        user_description="느리고 정교한 사고를 오래 유지할 수 있도록 돕는 환경입니다. 기획, 연구, 구조 설계, 철학적 정리처럼 긴 호흡의 사고가 필요한 순간에 적합합니다.",
        category="deliberate-thinking",
        session_duration_sec=1200,
        target_axes={
            "focus_readiness": 0.76,
            "stress_load": 0.18,
            "fatigue_risk": 0.28,
            "relaxation_level": 0.62,
            "cortical_arousal": 0.38,
            "mental_workload": 0.58,
        },
        style_bias={"warmth": 0.38, "novelty": 0.18, "motion": 0.22, "density": 0.46},
        lighting_defaults={
            "primary_hex": "#c9d0ff",
            "secondary_hex": "#f0debd",
            "accent_hex": "#f7f2ea",
            "brightness_percent": 40,
            "cct_kelvin": 3500,
            "motion_intensity": 0.22,
            "pulse_bpm": 64,
            "pattern": "ring-drift",
        },
        music_defaults={
            "bpm_target": 62,
            "bpm_min": 56,
            "bpm_max": 68,
            "key_scale": "D Dorian",
            "time_signature": "4",
            "energy": 0.24,
            "rhythmic_density": 0.16,
            "spectral_brightness": 0.28,
            "harmonic_tension": 0.20,
            "repetition": 0.76,
            "texture_density": 0.44,
            "dynamic_range": 0.22,
            "attack_softness": 0.88,
            "instruments": ["glass pad", "distant piano", "soft sub pulse", "slow evolving texture"],
            "avoid": ["busy hi-hats", "vocal chops", "aggressive bass"],
        },
    ),
    "uranus": PlanetProfile(
        slug="uranus",
        title="Uranus",
        goal_label="전환형 창의",
        user_description="익숙한 방식에서 벗어나 새로운 관점으로 사고를 전환하도록 돕는 환경입니다. 막힌 아이디어를 깨고, 발상 전환이나 실험적 접근이 필요할 때 어울립니다.",
        category="disruptive-creativity",
        session_duration_sec=780,
        target_axes={
            "focus_readiness": 0.60,
            "stress_load": 0.26,
            "fatigue_risk": 0.20,
            "relaxation_level": 0.46,
            "cortical_arousal": 0.60,
            "mental_workload": 0.45,
        },
        style_bias={"warmth": 0.34, "novelty": 0.84, "motion": 0.54, "density": 0.40},
        lighting_defaults={
            "primary_hex": "#7ddff2",
            "secondary_hex": "#c7f5ff",
            "accent_hex": "#e8fff7",
            "brightness_percent": 58,
            "cct_kelvin": 4600,
            "motion_intensity": 0.52,
            "pulse_bpm": 88,
            "pattern": "shift-glimmer",
        },
        music_defaults={
            "bpm_target": 90,
            "bpm_min": 82,
            "bpm_max": 98,
            "key_scale": "A Minor",
            "time_signature": "4",
            "energy": 0.50,
            "rhythmic_density": 0.34,
            "spectral_brightness": 0.50,
            "harmonic_tension": 0.36,
            "repetition": 0.52,
            "texture_density": 0.42,
            "dynamic_range": 0.30,
            "attack_softness": 0.62,
            "instruments": ["modular plucks", "airy pad", "glitch-spark texture", "soft pulse"],
            "avoid": ["overly stable loop", "anthemic vocals", "marching drums"],
        },
    ),
    "neptune": PlanetProfile(
        slug="neptune",
        title="Neptune",
        goal_label="딥워크 몰입",
        user_description="외부 잡음을 최대한 줄이고 좁고 깊은 집중 상태로 들어가도록 설계된 환경입니다. 코딩, 독서, 논문, 분석처럼 높은 몰입 밀도가 필요한 작업에 적합합니다.",
        category="deep-work",
        session_duration_sec=1200,
        target_axes={
            "focus_readiness": 0.88,
            "stress_load": 0.14,
            "fatigue_risk": 0.20,
            "relaxation_level": 0.58,
            "cortical_arousal": 0.40,
            "mental_workload": 0.64,
        },
        style_bias={"warmth": 0.26, "novelty": 0.16, "motion": 0.26, "density": 0.34},
        lighting_defaults={
            "primary_hex": "#4eb7ff",
            "secondary_hex": "#8fd4ff",
            "accent_hex": "#e7f5ff",
            "brightness_percent": 34,
            "cct_kelvin": 3900,
            "motion_intensity": 0.24,
            "pulse_bpm": 66,
            "pattern": "deep-current",
        },
        music_defaults={
            "bpm_target": 66,
            "bpm_min": 60,
            "bpm_max": 72,
            "key_scale": "C Minor",
            "time_signature": "4",
            "energy": 0.22,
            "rhythmic_density": 0.14,
            "spectral_brightness": 0.22,
            "harmonic_tension": 0.16,
            "repetition": 0.82,
            "texture_density": 0.32,
            "dynamic_range": 0.20,
            "attack_softness": 0.90,
            "instruments": ["soft synth pad", "subtle piano", "low pulse", "air texture"],
            "avoid": ["lead vocals", "snare-heavy drums", "bright plucks"],
        },
    ),
    "pluto": PlanetProfile(
        slug="pluto",
        title="Pluto",
        goal_label="회복과 리셋",
        user_description="긴장을 낮추고 감각을 천천히 가라앉히며 하루를 정리하도록 돕는 환경입니다. 과부하 이후 회복, 정서적 안정, 전환이 필요한 시간에 가장 잘 맞습니다.",
        category="recovery-reset",
        session_duration_sec=900,
        target_axes={
            "focus_readiness": 0.22,
            "stress_load": 0.08,
            "fatigue_risk": 0.20,
            "relaxation_level": 0.88,
            "cortical_arousal": 0.16,
            "mental_workload": 0.12,
        },
        style_bias={"warmth": 0.52, "novelty": 0.10, "motion": 0.12, "density": 0.22},
        lighting_defaults={
            "primary_hex": "#7b8fb8",
            "secondary_hex": "#c9d1f2",
            "accent_hex": "#f2f4fb",
            "brightness_percent": 22,
            "cct_kelvin": 2900,
            "motion_intensity": 0.10,
            "pulse_bpm": 52,
            "pattern": "slow-fade",
        },
        music_defaults={
            "bpm_target": 54,
            "bpm_min": 48,
            "bpm_max": 60,
            "key_scale": "Bb Major",
            "time_signature": "4",
            "energy": 0.10,
            "rhythmic_density": 0.06,
            "spectral_brightness": 0.16,
            "harmonic_tension": 0.08,
            "repetition": 0.86,
            "texture_density": 0.24,
            "dynamic_range": 0.16,
            "attack_softness": 0.96,
            "instruments": ["breathing pad", "soft drone", "distant bell haze", "slow felt resonance"],
            "avoid": ["kick drum", "vocal adlibs", "aggressive highs"],
        },
    ),
}


def get_planet_profile(planet: str) -> PlanetProfile:
    slug = str(planet or "").strip().lower()
    if slug not in PLANET_PROFILES:
        raise ValueError(f"unsupported planet: {planet}")
    return PLANET_PROFILES[slug]
