export const PLANET_LIGHTING_PREVIEW = {
  mercury: {
    programLabel: 'Ignition Focus Lighting',
    summary: '작업 진입 저항을 낮추기 위해 짧은 쿨 램프를 거친 뒤, 산만함을 줄이는 정적 집중광으로 고정합니다.',
    researchAnchor: '6500 K 계열 · 850-1000 lx 클래스',
    evidenceLabel: '직접 논문값 + 저강도 패턴 추론',
    deviceProfile: 'generic-rgb',
    cctKelvin: 6200,
    luxAnchor: 850,
    brightnessPercent: 72,
    primaryHex: '#fff3dc',
    secondaryHex: '#ffb34d',
    accentHex: '#ffe28e',
    patternLabel: 'Cool Ramp',
    patternEvidence: 'inferred',
    patternCadence: '90초 사이클',
    phases: [
      {
        label: 'Entry Ramp',
        durationText: '초기 진입',
        cctKelvin: 6500,
        luxAnchor: 1000,
        brightnessPercent: 78,
        patternLabel: 'Cool Ramp',
        primaryHex: '#fff9e9',
        secondaryHex: '#ffb34d',
        accentHex: '#fff1c6',
      },
      {
        label: 'Focus Hold',
        durationText: '집중 유지',
        cctKelvin: 5800,
        luxAnchor: 700,
        brightnessPercent: 64,
        patternLabel: 'Static Hold',
        primaryHex: '#ffefdb',
        secondaryHex: '#ffc46d',
        accentHex: '#fff3d2',
      },
    ],
    citations: [
      { label: 'Zhou 2021', url: 'https://pubmed.ncbi.nlm.nih.gov/34164367/' },
      { label: 'Ishii 2015', url: 'https://pubmed.ncbi.nlm.nih.gov/26098084/' },
      { label: 'Bao 2021', url: 'https://www.nature.com/articles/s41598-021-94795-0' },
    ],
  },
  venus: {
    programLabel: 'Warm Creativity Lighting',
    summary: '3000K 계열의 따뜻한 조명으로 감정적 긴장을 낮추고, 아이디어 연상이 이어지도록 밝기를 확보합니다.',
    researchAnchor: '3000 K · 590 lx',
    evidenceLabel: '직접 논문값 + 저강도 패턴 추론',
    deviceProfile: 'generic-rgb',
    cctKelvin: 3000,
    luxAnchor: 590,
    brightnessPercent: 56,
    primaryHex: '#ffb67c',
    secondaryHex: '#ffb8c8',
    accentHex: '#ffd7a8',
    patternLabel: 'Warm Bloom',
    patternEvidence: 'inferred',
    patternCadence: '180초 사이클',
    phases: [
      {
        label: 'Creative Warm Field',
        durationText: '세션 전반',
        cctKelvin: 3000,
        luxAnchor: 590,
        brightnessPercent: 56,
        patternLabel: 'Warm Bloom',
        primaryHex: '#ffb67c',
        secondaryHex: '#ffb8c8',
        accentHex: '#ffd7a8',
      },
    ],
    citations: [
      { label: 'Ishii 2015', url: 'https://pubmed.ncbi.nlm.nih.gov/26098084/' },
      { label: 'Chen et al. 2022', url: 'https://www.mdpi.com/1685704' },
      { label: 'Choi 2014', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3897760/' },
    ],
  },
  earth: {
    programLabel: 'Balanced Sustain Lighting',
    summary: '중간 색온도와 밝은 조도 조합으로 장시간 업무에서 편안함과 생산성 균형을 맞춥니다.',
    researchAnchor: '4200 K · 500 lx',
    evidenceLabel: '직접 논문값',
    deviceProfile: 'generic-rgb',
    cctKelvin: 4200,
    luxAnchor: 500,
    brightnessPercent: 58,
    primaryHex: '#f4d5b1',
    secondaryHex: '#8fe3c2',
    accentHex: '#8db5ff',
    patternLabel: 'Balanced Hold',
    patternEvidence: 'direct_values',
    patternCadence: '정적 유지',
    phases: [
      {
        label: 'Balanced Focus Field',
        durationText: '세션 전반',
        cctKelvin: 4200,
        luxAnchor: 500,
        brightnessPercent: 58,
        patternLabel: 'Balanced Hold',
        primaryHex: '#f4d5b1',
        secondaryHex: '#8fe3c2',
        accentHex: '#8db5ff',
      },
    ],
    citations: [
      { label: 'Chen et al. 2022', url: 'https://www.mdpi.com/1685704' },
      { label: 'Bao 2021', url: 'https://www.nature.com/articles/s41598-021-94795-0' },
    ],
  },
  mars: {
    programLabel: 'Action Drive Lighting',
    summary: '결단과 실행을 위해 6500K 클래스의 밝은 조명을 유지하되, 패턴은 짧은 램프 수준으로만 제한합니다.',
    researchAnchor: '6500 K · 1000 lx',
    evidenceLabel: '직접 논문값 + 저강도 패턴 추론',
    deviceProfile: 'generic-rgb',
    cctKelvin: 6500,
    luxAnchor: 1000,
    brightnessPercent: 82,
    primaryHex: '#fff1e8',
    secondaryHex: '#ff7459',
    accentHex: '#ffc08a',
    patternLabel: 'Cool Ramp',
    patternEvidence: 'inferred',
    patternCadence: '90초 사이클',
    phases: [
      {
        label: 'Action Push',
        durationText: '고각성 실행',
        cctKelvin: 6500,
        luxAnchor: 1000,
        brightnessPercent: 84,
        patternLabel: 'Cool Ramp',
        primaryHex: '#ffece3',
        secondaryHex: '#ff7459',
        accentHex: '#ffd8ad',
      },
    ],
    citations: [
      { label: 'Zhou 2021', url: 'https://pubmed.ncbi.nlm.nih.gov/34164367/' },
      { label: 'Ishii 2015', url: 'https://pubmed.ncbi.nlm.nih.gov/26098084/' },
      { label: 'Bao 2021', url: 'https://www.nature.com/articles/s41598-021-94795-0' },
    ],
  },
  jupiter: {
    programLabel: 'Strategic Presence Lighting',
    summary: '과도한 자극 없이 의사결정과 발표 준비에 맞춘 차분한 쿨 브라이트 톤으로 설계합니다.',
    researchAnchor: '5000 K · 650 lx',
    evidenceLabel: '직접 논문값 기반 중간 조합 + 저강도 패턴 추론',
    deviceProfile: 'generic-rgb',
    cctKelvin: 5000,
    luxAnchor: 650,
    brightnessPercent: 66,
    primaryHex: '#fbe0c6',
    secondaryHex: '#f0c46a',
    accentHex: '#d7b0ff',
    patternLabel: 'Command Wave',
    patternEvidence: 'inferred',
    patternCadence: '150초 사이클',
    phases: [
      {
        label: 'Strategic Field',
        durationText: '세션 전반',
        cctKelvin: 5000,
        luxAnchor: 650,
        brightnessPercent: 66,
        patternLabel: 'Command Wave',
        primaryHex: '#fbe0c6',
        secondaryHex: '#f0c46a',
        accentHex: '#d7b0ff',
      },
    ],
    citations: [
      { label: 'Zhou 2021', url: 'https://pubmed.ncbi.nlm.nih.gov/34164367/' },
      { label: 'Bao 2021', url: 'https://www.nature.com/articles/s41598-021-94795-0' },
      { label: 'Chen et al. 2022', url: 'https://www.mdpi.com/1685704' },
    ],
  },
  saturn: {
    programLabel: 'Deliberate Thinking Lighting',
    summary: '낮은 mental workload가 보고된 3000K/750lx 조합을 기준으로 장시간 사고와 구조화에 맞춥니다.',
    researchAnchor: '3000 K · 750 lx',
    evidenceLabel: '직접 논문값',
    deviceProfile: 'generic-rgb',
    cctKelvin: 3000,
    luxAnchor: 750,
    brightnessPercent: 62,
    primaryHex: '#fbb475',
    secondaryHex: '#c9d0ff',
    accentHex: '#f0debd',
    patternLabel: 'Static Focus Hold',
    patternEvidence: 'direct_values',
    patternCadence: '정적 유지',
    phases: [
      {
        label: 'Low-workload Reasoning Field',
        durationText: '세션 전반',
        cctKelvin: 3000,
        luxAnchor: 750,
        brightnessPercent: 62,
        patternLabel: 'Static Focus Hold',
        primaryHex: '#fbb475',
        secondaryHex: '#c9d0ff',
        accentHex: '#f0debd',
      },
    ],
    citations: [
      { label: 'Bao 2021', url: 'https://www.nature.com/articles/s41598-021-94795-0' },
      { label: 'Choi 2014', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3897760/' },
    ],
  },
  uranus: {
    programLabel: 'Perspective Shift Lighting',
    summary: '기본은 warm-creative 조합을 유지하고, 아주 느린 warm-cool drift로 발상 전환만 보조합니다.',
    researchAnchor: '3200 K · 620 lx',
    evidenceLabel: '직접 논문값 + 패턴은 저근거 추론',
    deviceProfile: 'generic-rgb',
    cctKelvin: 3200,
    luxAnchor: 620,
    brightnessPercent: 60,
    primaryHex: '#f2be88',
    secondaryHex: '#7ddff2',
    accentHex: '#e8fff7',
    patternLabel: 'Contrast Drift',
    patternEvidence: 'inferred',
    patternCadence: '120초 사이클',
    phases: [
      {
        label: 'Creative Contrast Field',
        durationText: '세션 전반',
        cctKelvin: 3200,
        luxAnchor: 620,
        brightnessPercent: 60,
        patternLabel: 'Contrast Drift',
        primaryHex: '#f2be88',
        secondaryHex: '#7ddff2',
        accentHex: '#e8fff7',
      },
    ],
    citations: [
      { label: 'Ishii 2015', url: 'https://pubmed.ncbi.nlm.nih.gov/26098084/' },
      { label: 'Chen et al. 2022', url: 'https://www.mdpi.com/1685704' },
    ],
  },
  neptune: {
    programLabel: 'Deep Work Lighting',
    summary: '차갑지만 과격하지 않은 쿨 뉴트럴 톤으로 몰입을 유지하고, 패턴은 제거해 시각 노이즈를 최소화합니다.',
    researchAnchor: '5000 K · 650 lx',
    evidenceLabel: '직접 논문값',
    deviceProfile: 'generic-rgb',
    cctKelvin: 5000,
    luxAnchor: 650,
    brightnessPercent: 48,
    primaryHex: '#f2e1d3',
    secondaryHex: '#6ecbff',
    accentHex: '#dff4ff',
    patternLabel: 'Static Focus Hold',
    patternEvidence: 'direct_values',
    patternCadence: '정적 유지',
    phases: [
      {
        label: 'Deep Focus Field',
        durationText: '기본 몰입',
        cctKelvin: 5000,
        luxAnchor: 650,
        brightnessPercent: 48,
        patternLabel: 'Static Focus Hold',
        primaryHex: '#f2e1d3',
        secondaryHex: '#6ecbff',
        accentHex: '#dff4ff',
      },
      {
        label: 'Deepen Hold',
        durationText: '더 좁은 몰입',
        cctKelvin: 4800,
        luxAnchor: 550,
        brightnessPercent: 44,
        patternLabel: 'Static Focus Hold',
        primaryHex: '#f2ddcd',
        secondaryHex: '#78c9ff',
        accentHex: '#edf8ff',
      },
    ],
    citations: [
      { label: 'Ishii 2015', url: 'https://pubmed.ncbi.nlm.nih.gov/26098084/' },
      { label: 'Bao 2021', url: 'https://www.nature.com/articles/s41598-021-94795-0' },
      { label: 'Zhou 2021', url: 'https://pubmed.ncbi.nlm.nih.gov/34164367/' },
    ],
  },
  pluto: {
    programLabel: 'Recovery Reset Lighting',
    summary: '급성 스트레스 직후에는 짧은 blue decompress를 쓰고, 이후에는 따뜻하고 어두운 recovery hold로 즉시 내려앉힙니다.',
    researchAnchor: '초기 blue decompress 후 2700 K · 120 lx 복귀',
    evidenceLabel: '값은 직접 논문 기반, 호흡 패턴은 추론',
    deviceProfile: 'generic-rgb',
    cctKelvin: 2700,
    luxAnchor: 120,
    brightnessPercent: 16,
    primaryHex: '#f7ad69',
    secondaryHex: '#c9d1f2',
    accentHex: '#f2f4fb',
    patternLabel: 'Resonance Breath',
    patternEvidence: 'inferred',
    patternCadence: '6 breaths/min',
    phases: [
      {
        label: 'Post-stress Decompression',
        durationText: '초기 1-5분',
        cctKelvin: 5000,
        luxAnchor: 80,
        brightnessPercent: 18,
        patternLabel: 'Resonance Breath',
        primaryHex: '#dfd9da',
        secondaryHex: '#84c6ff',
        accentHex: '#dff4ff',
      },
      {
        label: 'Recovery Hold',
        durationText: '지속 회복',
        cctKelvin: 2700,
        luxAnchor: 120,
        brightnessPercent: 16,
        patternLabel: 'Resonance Breath',
        primaryHex: '#f8ad69',
        secondaryHex: '#d8d9e8',
        accentHex: '#f6efe8',
      },
    ],
    citations: [
      { label: 'Castillo 2017', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5648169/' },
      { label: 'Choi 2014', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3897760/' },
      { label: 'Laborde 2021', url: 'https://pubmed.ncbi.nlm.nih.gov/33658964/' },
    ],
  },
};
