mindmap
  root((State Profile))
    focus_readiness
      집중 준비도
    stress_load
      긴장과 압박
    fatigue_risk
      피로와 졸림 위험
    relaxation_level
      이완 수준
    cortical_arousal
      각성 수준
    mental_workload
      인지적 작업부하
